# Generated by Django 4.2.7 on 2026-01-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_add_location_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionpoint',
            name='location',
        ),
        migrations.RemoveField(
            model_name='collectionpoint',
            name='location_coordinates',
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude', max_digits=9, null=True),
        ),
    ]
