# Generated by Django 4.2.7 on 2026-01-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='location',
            field=models.TextField(blank=True, help_text='GPS location coordinates (will be PointField when GeoDjango is enabled)', null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='location',
            field=models.TextField(blank=True, help_text='GPS location coordinates (will be PointField when GeoDjango is enabled)', null=True),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='location_coordinates',
            field=models.CharField(blank=True, help_text='Legacy: Latitude,Longitude', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='location_coordinates',
            field=models.CharField(blank=True, help_text='Legacy: Latitude,Longitude (e.g., -1.2921,36.8219)', max_length=100, null=True),
        ),
    ]
