# Generated by Django 4.2.7 on 2026-01-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_verificationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='buyers/'),
        ),
    ]
