# Generated by Django 4.2.7 on 2026-01-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_video_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.TextField(blank=True, help_text='GPS location coordinates (will be PointField when GeoDjango is enabled)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='location_coordinates',
            field=models.CharField(blank=True, help_text='Legacy: Latitude,Longitude', max_length=100, null=True),
        ),
    ]
