# Generated by Django 4.2.7 on 2026-01-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('available', 'Available'), ('rejected', 'Rejected'), ('pending_sale', 'Pending Sale'), ('sold', 'Sold'), ('expired', 'Expired')], default='pending_approval', max_length=20),
        ),
    ]
